define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    WeeksOnLabel: "week(s) on",
    PaternLabel: "Pattern",
    OcurrencesLabel: "Ocurrences",
    DateRangeLabel: "Date Range",
    WeekendDayLabel: "Weekend Day",
    WeekDayLabel: "Weekday",
    LastLabel: "last",
    FourthLabel: "fourth",
    ThirdLabel: "third",
    SecondLabel: "second",
    FirstLabel: "first",
    TheLabel: "the",
    MonthsLabel: "month(s)",
    OfEveryLabel: "of every ",
    AllowedValues1to12Label: "Allowed values 1 to 12",
    NoEndDate: "no end date",
    everyweekdayLabel: "every weekday",
    daysLabel: "days",
    EveryLabel: "every",
    OnEveryLabel: "On every",
    EndByLabel: "end by",
    EndAfterLabel: "end after",
    HttpErrorMessage: "Error reading calendar events:",
    CategoryPlaceHolder: "Please select category",
    CategoryLabel: "Category",
    EnDateValidationMessage: "start date is greater than end date",
    SartDateValidationMessage: "start date is greater than end date",
    eventSelectDatesLabel: "Show only the events within the following dates",
    ConfirmDeleteSeriesMsg: "Confirm to delete a series ? You will be deleting all related events of the series",
    ConfirmDeleteEventMsg: "Confirm to delete an event ? You will be deleting a single event",
    ConfirmDeleteSeriesEventMsg: "Confirm to delete an event ? You will be deleting a single event of a series",
    ConfirmUpdateSeriesMsg: "Confirm to update a series ? You will be updating all related events of the series",
    ConfirmUpdateEventMsg: "Confirm to update an event ? You will be updating a single event",
    ConfirmUpdateSeriesEventMsg: "Confirm to update an event ? You will be updating a single event of a series",
    DialogConfirmDeleteTitle: "Delete Event",
    SpinnerDeletingLabel: "Deleting...",
    SpinnerUpdatingLabel: "Deleting...",
    DialogCloseButtonLabel: "Cancel",
    DialogConfirmDeleteLabel: "Delete",
    DeleteEventLabel:"Delete Event",
    SaveButtonLabel: "Save",
    DeleteButtonLabel: "Delete",
    DeleteSeriesLabel:"Delete series",
    DeleteOccurrenceLabel: "Delete Occurrence",
    EditButtonLabel: "Edit",
    EditSeriesLabel: "Edit series",
    EditOccurrenceLabel: "Edit Occurrence",
    CancelButtonLabel: "Cancel",
    SubmitButtonLabel: "Submit",
    OkButtonLabel: "Ok",
    LoadingEventsLabel: "Loading events...",
    WebPartConfigButtonLabel: "Configure",
    WebpartConfigDescription: "Please configure list calendar ",
    WebpartConfigIconText: "Configure your Calendar Web Part",
    EventOwnerLabel: "event owner",
    InvalidDateFormatMsg: "Invalid date format.",
    IsRequiredMsg: "Field is required.",
    CloseDateLabel: "Close date picker",
    NextYearLabel: "Go to next year",
    PrevYearLabel: "Go to previous year",
    NextMonthLabel: "Go to next month",
    PrevMonthLabel: "Go to previous month",
    GoToDayLabel: "Go to today",
    ShortDay_SuLabel: "S",
    ShortDay_FrLabel: "F",
    ShortDay_ThLabel: "T",
    ShortDay_WeLabel: "W",
    ShortDay_TuLabel: "T",
    ShortDay_MoLabel: "M",
    ShortDay_SaLabel: "S",
    SaturdayLabel: "Saturday",
    FridayLabel: "Friday",
    ThursdayLabel: "Thursday",
    WednesdayLabel:"Wednesday",
    TuesdayLabel: "Tuesday",
    MondayLabel: "Monday",
    SundayLabel: "Sunday",
    JanLabel:"Jan",
    FebLabel:"Feb",
    MarLabel:"Mar",
    AprLabel:"Apr",
    MayLabel:"May",
    JunLabel:"Jun",
    JulLabel:"Jul",
    AugLabel:"Aug",
    SepLabel:"Sep",
    OctLabel:"Oct",
    NovLabel:"Nov",
    DecLabel:"Dec",
    DecemberLabel: "December",
    NovemberLabel: "November",
    OctoberLabel: "October",
    SeptemberLabel: "September",
    AugustLabel: "August",
    JulyLabel: "July",
    JuneLabel: "June",
    AprilLabel: "April",
    MarchLabel: "March",
    FebruaryLabel: "February",
    JanuaryLabel: "January",
    LocationLabel: "Location search and Map",
    LocationTextLabel: "Location",
    AttendeesLabel: "Attendees",
    EndMinLabel: "Min",
    EndHourLabel: "Hour",
    EndDateLabel: "End Date",
    EndDatePlaceHolder: "Select a date...",
    StartMinLabel: "Min",
    StartHourLabel: "Hour",
    StartDateLabel: "Start Date",
    StartDatePlaceHolder: "Select a date...",
    EventTitleErrorMessage: "Event Title is required.",
    EventTitleLabel: "Event title",
    EventPanelTitle: "Edit/Add Event",
    SiteUrlFieldLabel: "Site Url",
    ListFieldLabel: "Calendar List name",
    yearHeaderLabel: "Year",
    monthLabel: "Month",
    weekLabel: "Week",
    DayLabel: "Day",
    agenda: "Agenda",
    todayLabel: "Today",
    previousLabel: "Previous",
    nextLabel: "Next",
    showMore: "more",
    recurrenceEventLabel: "Recurrence Event",
    editRecurrenceSeries: "Edit Recurrence Series",
    AllDayEventLabel: "All Day",
    ifRecurrenceLabel: "Recurrence ?",
    OnLabel: "On",
    OffLabel: "Off",
    EventDescriptionLabel: "Event Description",
    recurrenceInformationLabel: "Recurrence Information",
    DailyLabel: "Daily",
    WeeklyLabel: "Weekly",
    MonthlyLabel: "Monthly",
    YearlyLabel: "Yearly",
    PatternLabel: "Pattern",
    occurrencesLabel: "occurrences",
    ofMonthLabel: "of",
    everyFormat: "Every {0} ",
    everySecondFormat: "Every {0} ",
    everyNthFormat: "Every {0} ",
    onTheDayFormat: "on the {0}th day",
    OnTheLabel: "on the",
    theSuffix: "",
    yearLabel: "year",
    theNthOfMonthFormat: "on {0} {1}",
    onTheDayTypeFormat: "on the {0} {1}",
    MenuLabel: "Menu",
    HelpLabel:"Help",
    FeedbackLabel:"Give feedback",
    EditMenuLabel:"Edit Menu",
    DeleteMenuLabel:"Delete Menu",
    AddNewEventLabel: "Add New Event",
    EditEventSeriesLabel: "Edit Event Series",
    EditSingleEventLabel: "Edit single Event From Series",
    EditEventlabel: "Edit An Event",
    ViewEventLabel: "View An Event",
    ShowLessLabel: "Show less options",
    ShowMoreLabel: "Show more options",
    Repeatlabel: 'Repeat',
    DayValidationMessage: "Allowed values 1 to 31",
    MonthValidationMessage: "Allowed values 1 to 12",
    InstancesValidationMsg: "Allowed values 1 to 999",
    WeekFrequencyValidationMsg: "Allowed values 1 to 255",
    SelectDateLabel: "Select a date...",
    FeedbackBoxLabel: "What would you like to tell us?",
    FeedbackCategoryLabel: "Feedback Category:",
    FeedbackCategoryToggleLabel: "Show Feedback Category",
    FeedbackInstructions: "By pressing submit, your feedback will be used to improve this widget. Your IT admin will be able to collect this data. Based on your feedback, we may provide additional information to help you with your support issue.",
    FeedbackSuccessMsg: "Feedback successfully submitted.",
    FeedbackAdminNotFoundMsg: "Feedback administrator was not found. Please ask your Portal administrator to setup the Feedback Admin group"
  }
});
