declare interface IBizpcompsLibraryStrings {
  PropertyPaneDescription: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  WeeksOnLabel: string;
  PaternLabel: string;
  OcurrencesLabel: string;
  WeekendDayLabel: string;
  WeekDayLabel: string;
  LastLabel: string;
  FourthLabel: string;
  ThirdLabel: string;
  SecondLabel: string;
  FirstLabel: string;
  TheLabel: string;
  MonthsLabel: string;
  OfEveryLabel: string;
  OnEveryLabel: string;
  EveryLabel: string;
  AllowedValues1to12Label: string;
  DayValidationMessage: string;
  MonthValidationMessage: string;
  InstancesValidationMsg: string;
  NoEndDate: string;
  everyweekdays: string;
  everyweekdayLabel: string;
  days: string;
  daysLabel: string;
  every: string;
  EndByLabel: string;
  EndAfterLabel: string;
  HttpErrorMessage: string;
  CategoryPlaceHolder: string;
  CategoryLabel: string;
  EnDateValidationMessage: string;
  SartDateValidationMessage: string;
  eventSelectDatesLabel: string;
  ConfirmDeleteSeriesMsg: string;
  ConfirmDeleteEventMsg: string;
  ConfirmDeleteSeriesEventMsg: string;
  ConfirmUpdateSeriesMsg: string;
  ConfirmUpdateEventMsg: string;
  ConfirmUpdateSeriesEventMsg: string;
  DialogConfirmDeleteTitle: string;
  SpinnerDeletingLabel: string;
  SpinnerUpdatingLabel: string;
  DialogCloseButtonLabel: string;
  DialogConfirmDeleteLabel: string;
  DeleteMenuLabel:string;
  EditMenuLabel:string;
  MenuLabel:string;
  HelpLabel:string;
  FeedbackLabel:string;
  EditSeriesLabel: string;
  EditOccurrenceLabel: string;
  DeleteSeriesLabel: string;
  DeleteOccurrenceLabel: string;
  SaveButtonLabel: string;
  SubmitButtonLabel: string;
  OkButtonLabel: string;
  DeleteButtonLabel: string;
  EditButtonLabel:string;
  CancelButtonLabel: string;
  LoadingEventsLabel: string;
  WebPartConfigButtonLabel: string;
  WebpartConfigDescription: string;
  WebpartConfigIconText: string;
  EventOwnerLabel: string;
  InvalidDateFormatMsg: string;
  IsRequiredLabel: string;
  CloseDateLabel: string;
  NextYearLabel: string;
  PrevYearLabel: string;
  NextMonthLabel: string;
  PrevMonthLabel: string;
  GoToDayLabel: string;
  ShortDay_SaLabel: string;
  ShortDay_FrLabel: string;
  ShortDay_ThLabel: string;
  ShortDay_WeLabel: string;
  ShortDay_TuLabel: string;
  ShortDay_MoLabel: string;
  ShortDay_SuLabel: string;
  SaturdayLabel: string;
  FridayLabel: string;
  ThursdayLabel: string;
  WednesdayLabel: string;
  TuesdayLabel: string;
  MondayLabel: string;
  SundayLabel: string;
  JanLabel:string;
  FebLabel:string;
  MarLabel:string;
  AprLabel:string;
  MayLabel:string,
  JunLabel:string;
  JulLabel:string;
  AugLabel:string;
  SepLabel:string;
  OctLabel:string;
  NovLabel:string;
  DecLabel:string;
  DecemberLabel: string;
  NovemberLabel: string;
  OctoberLabel: string;
  SeptemberLabel: string;
  AugustLabel: string;
  JulyLabel: string;
  JuneLabel: string;
  AprilLabel: string;
  MarchLabel: string;
  FebruaryLabel: string;
  JanuaryLabel: string;
  LocationLabel: string;
  LocationTextLabel: string;
  AttendeesLabel: string;
  EndMinLabel: string;
  EndHourLabel: string;
  EndDateLabel: string;
  EndDatePlaceHolder: string;
  StartMinLabel: string;
  StartHourLabel: string;
  StartDateLabel: string;
  StartDatePlaceHolder: string;
  EventTitleErrorMessage: string;
  EventTitleLabel: string;
  EventPanelTitle: string;
  SiteUrlFieldLabel: string;
  ListFieldLabel: string;
  yearHeaderLabel: string;
  monthLabel: string;
  weekLabel: string;
  DayLabel: string;
  agenda: string;
  todayLabel: string;
  previousLabel: string;
  nextLabel: string;
  showMore: string;
  recurrenceEventLabel: string;
  editRecurrenceSeries: string;
  AllDayEventLabel: string;
  ifRecurrenceLabel: string;
  OnLabel: string;
  OffLabel: string;
  EventDescriptionLabel: string;
  recurrenceInformationLabel: string;
  DailyLabel: string;
  WeeklyLabel: string;
  MonthlyLabel: string;
  YearlyLabel: string;
  PatternLabel: string;
  DateRangeLabel: string;
  occurrencesLabel: string;
  ofMonthLabel:string;
  everyFormat: string;
  everySecondFormat: string;
  everyNthFormat: string;
  onTheDayFormat: string;
  OnTheLabel: string;
  theSuffix: string;
  yearLabel: string;
  theNthOfMonthFormat: string;
  onTheDayTypeFormat: string;
  AddNewEventLabel: string;
  EditEventSeriesLabel: string;
  EditSingleEventLabel: string;
  DeleteEventLabel:string;
  EditEventlabel: string;
  ViewEventLabel: string;
  ShowLessLabel: string;
  ShowMoreLabel: string;
  Repeatlabel: string;
  SelectDateLabel:string;
  WeekFrequencyValidationMsg:string;
  FeedbackBoxLabel: string;
  FeedbackCategoryLabel: string;
  FeedbackCategoryToggleLabel: string;
  FeedbackInstructions: string;
  FeedbackSuccessMsg: string;
  FeedbackAdminNotFoundMsg: string;
}

 declare module 'BizpcompsLibraryStrings' {
  const strings: IBizpcompsLibraryStrings;
  export = strings;
}

// export= 'BizpcompsLibraryStrings';

